// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCinhfbxeJDFZ7QscJrxR0TeHv0JAWzdXM',
    appId: '1:493586243299:android:0d074e398fcac162ff6fd6',
    messagingSenderId: '493586243299',
    projectId: 'variouslogin-ef5b6',
    databaseURL: 'https://variouslogin-ef5b6.firebaseio.com',
    storageBucket: 'variouslogin-ef5b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC8pWkX2W9Iwc71MGTe_-pCiVpVZeRD-E',
    appId: '1:493586243299:ios:4ad481ba77d180abff6fd6',
    messagingSenderId: '493586243299',
    projectId: 'variouslogin-ef5b6',
    databaseURL: 'https://variouslogin-ef5b6.firebaseio.com',
    storageBucket: 'variouslogin-ef5b6.firebasestorage.app',
    iosBundleId: 'com.cjy.hellchinza.dev',
  );
}
